//COMMON
export const FETCH_START = 'FETCH_START';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_ERROR = 'FETCH_ERROR';
export const HIDE_MESSAGE = 'HIDE_MESSAGE';
export const SHOW_MESSAGE = 'SHOW_MESSAGE';

//CONCEPTO
export const LIST_CONCEPTO = "LIST_CONCEPTO";
export const CONCEPT_STATUS_ACTIONS = "CONCEPT_STATUS_ACTIONS";
export const GET_CONCEPT = "GET_CONCEPT";

//DESCUENTO
export const GET_DESCUENTO = "GET_DESCUENTO"
export const CHECKING_DESCUENTO = "CHECKING_DESCUENTO"

//IZIDATA
export const FORMDATAIZI = "FORMDATAIZI"
export const ERROR_MESSAGE_IZI = "ERROR_MESSAGE_IZI"

//PEDIDO
export const SUCCESS_SAVE_PEDIDO = "SUCCESS_SAVE_PEDIDO"
export const SAVING_PEDIDO = "SAVING_PEDIDO"
export const PEDIDO_DATA = "PEDIDO_DATA"
export const PEDIDO_ERRORS = "PEDIDO_ERRORS"

//CURSOS
export const LIST_CURSO = "LIST_CURSO"

//NOTICIAS
export const LIST_NOTICIA = "LIST_NOTICIA"
export const GET_NOTICIA = "GET_NOTICIA"

//PRONUNCIAMIENTOS
export const LIST_PRONUNCIAMIENTO = "LIST_PRONUNCIAMIENTO"

//NOTICIAS
export const LIST_REVISTADIGITAL = "LIST_REVISTADIGITAL"
export const GET_REVISTADIGITAL = "GET_REVISTADIGITAL"

//ACTIVIDADES
export const LIST_ACTIVIDAD = "LIST_ACTIVIDAD"
export const SHOW_ACTIVIDAD = "SHOW_ACTIVIDAD"

//PROMOTOR
export const FILTER_PROMOTOR = "FILTER_PROMOTOR"
export const LOADING_PROMOTOR = "LOADING_PROMOTOR"

//COMITÉ GREMIALES
export const FILTER_COMITE_GREMIAL = "FILTER_COMITE_GREMIAL"
export const LOADING_COMITE_GREMIAL = "LOADING_COMITE_GREMIAL"

//ASOCIADO
export const SHOW_RUC_SEARCHED = "SHOW_RUC_SEARCHED"
export const LOADING_RUC_SEARCH = "LOADING_RUC_SEARCH"
export const HAS_RUC_SEARCHED = "HAS_RUC_SEARCHED"
export const LOADING_SAVING_AFILIATION = "LOADING_SAVING_AFILIATION"
export const AFILIATION_SAVED = "AFILIATION_SAVED"